export const UPDATE_FADER = "UPDATE_FADER";
export const UPDATE_SWITCH = "UPDATE_SWITCH";
export const SET_DRAG_POINT = "SET_DRAG_POINT";
export const MAKE_CONNECTION = "MAKE_CONNECTION";

export const SET_MIDI_INPUT = "SET_MIDI_INPUT";
export const SET_MIDI_OUTPUT = "SET_MIDI_OUTPUT"